### ISSUE TITLE
Set a default limit on the number of items returned.

### ISSUE THREAD

**Issue by ingeniousgenius** [CompanyCam/graphql-searchkick#5]
When a `first` parameter isn't provided as an argument to the search query, the query will return all of the records in the elastic search index, which could be thousands if not hundreds of thousands. There should be some default limit imposed on the number of items returned in case the client does leave out the `first` parameter.

My suggestion would to be add something like this to the `apply_pagination` method in the `GraphQL::Searchkick::ResultConnection`

```ruby
      if first
        set_limit(nodes, first) if search_limit(nodes).nil? || search_limit(nodes) > first
      else
        set_limit(nodes, 15) # possibly get max limit from schema opposed to magic number
      end
```

All that does there is check if there's a limit and if not apply a default limit. It would be useful to implement something like this.

**Comment by chadwilken** [comment]
I think using the `max_page_size` from the schema would make sense and if that isn't set then it's kinda on them IMO. I'm getting ready to add support for the new pagination classes and I will try to get to this while working on that unless you want to open a PR.

**Comment by chadwilken** [comment]
@jesster2k10 I was going back through the code and it does apply some default limiting if you have a `max_page_size` set on your schema: https://github.com/CompanyCam/graphql-searchkick/blob/master/lib/graphql/searchkick/result_connection.rb#L106

**Comment by ingeniousgenius** [comment]
> @jesster2k10 I was going back through the code and it does apply some default limiting if you have a `max_page_size` set on your schema: https://github.com/CompanyCam/graphql-searchkick/blob/master/lib/graphql/searchkick/result_connection.rb#L106

I’m not sure why that wasn’t applied for me. But i’ll try again, i just coped the connection file and modified it myself as a temporary workaround
